apiVersion: v1
kind: Service
metadata:
  name: t2v-transformers
  namespace: ai-workloads
  labels:
    app: t2v-transformers
spec:
  type: ClusterIP
  selector:
    app: t2v-transformers
  ports:
    - name: http
      port: 8080
      targetPort: 8080
