apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: ai-workloads
  labels:
    app: weaviate
spec:
  type: NodePort
  selector:
    app: weaviate
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Choose a port within the 30000-32767 range
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30051
